-- ============================================================
-- agent_config: prompts and thresholds owned by counsellors, not developers
-- (build step 14, ADR-0018).
--
-- This table is the answer to the requirement that put the agent in n8n in the
-- first place (ADR-0006): a non-developer changes the prompt and the routing
-- thresholds without a developer and without a deploy.
--
-- Versioned, never mutated. A save INSERTs version N+1 and flips is_active; a
-- revert flips is_active back to an earlier row. A bad edit at 17:00 on a
-- Friday must be revertable in one click, and the row that was live at the time
-- must still exist to revert *to*.
--
-- Read path: the public chat route reads the active row with the service key,
-- because the parent is anonymous and must never be able to read another
-- agency's prompt. Counsellors read and write it through RLS below.
-- ============================================================

CREATE TABLE IF NOT EXISTS agent_config (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  agency_id       UUID NOT NULL REFERENCES agencies(id) ON DELETE CASCADE,
  system_prompt   TEXT NOT NULL,
  -- {"low":25,"medium":50,"hot":75} — ADR-0017. `low` gates whether Stage 2
  -- runs at all; `medium`/`hot` are the only thresholds applied to a complete
  -- four-dimension score.
  bant_thresholds JSONB NOT NULL,
  -- Parent-visible copy that is NOT generated by the model: the turn-cap close
  -- and the two routing messages. Editable for the same reason the prompt is.
  routing_copy    JSONB NOT NULL,
  version         INTEGER NOT NULL,
  created_by      UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  is_active       BOOLEAN NOT NULL DEFAULT FALSE,
  UNIQUE (agency_id, version)
);

ALTER TABLE agent_config ENABLE ROW LEVEL SECURITY;

-- Exactly one active row per agency, enforced by the database rather than by
-- whichever query happens to run first. Without this, "the active config" is a
-- coin flip the moment two saves race.
CREATE UNIQUE INDEX IF NOT EXISTS idx_agent_config_one_active
  ON agent_config(agency_id) WHERE is_active;

-- The chat route's read on every turn.
CREATE INDEX IF NOT EXISTS idx_agent_config_agency_version
  ON agent_config(agency_id, version DESC);

-- ------------------------------------------------------------
-- leads.escalated_at — escalation idempotency
--
-- An Inngest step is retried on failure. Without a durable marker, a retry
-- after a partial failure sends the admissions team a second email about the
-- same family. Nullable with no default: NULL means "never escalated", which
-- is the correct state for every existing row.
-- ------------------------------------------------------------

ALTER TABLE leads ADD COLUMN IF NOT EXISTS escalated_at TIMESTAMPTZ;

-- ------------------------------------------------------------
-- RLS
--
-- Reuses current_agency_ids() from 20260915071821_add_agency_tenancy.sql rather
-- than re-deriving the membership subquery — one definition of "the tenant of
-- the current request", and it avoids the policy recursion documented there.
-- ------------------------------------------------------------

CREATE POLICY agent_config_agency_select ON agent_config FOR SELECT USING (
  agency_id IN (SELECT current_agency_ids())
);

-- Writing the prompt the product speaks with is an owner action, not a
-- counsellor one. A SECURITY DEFINER helper again, for the same recursion
-- reason: a policy that subqueries agency_members re-triggers that table's own
-- policy.
CREATE OR REPLACE FUNCTION current_owner_agency_ids()
RETURNS SETOF UUID
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, auth
AS $$
  SELECT agency_id FROM agency_members WHERE user_id = auth.uid() AND role = 'owner'
$$;

REVOKE ALL ON FUNCTION current_owner_agency_ids() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION current_owner_agency_ids() TO authenticated;

CREATE POLICY agent_config_owner_insert ON agent_config FOR INSERT WITH CHECK (
  agency_id IN (SELECT current_owner_agency_ids())
);

-- UPDATE exists only so revert can flip is_active. USING scopes what is
-- visible to change; WITH CHECK stops a row being updated *into* another
-- agency, the same reason leads_agency_update carries both.
CREATE POLICY agent_config_owner_update ON agent_config FOR UPDATE USING (
  agency_id IN (SELECT current_owner_agency_ids())
) WITH CHECK (
  agency_id IN (SELECT current_owner_agency_ids())
);

-- ------------------------------------------------------------
-- Grants
--
-- config.toml leaves auto_expose_new_tables unset, so a new table is not
-- reachable through the Data API roles without an explicit GRANT. RLS above is
-- what scopes the rows; this is what makes the table addressable at all.
-- No grant to anon: the parent-facing route reads this with the service key.
-- ------------------------------------------------------------

GRANT SELECT, INSERT, UPDATE ON agent_config TO authenticated;

-- ------------------------------------------------------------
-- Version 1 — ported from the n8n workflows this step retires
--
-- The prompt is src/agents/prompts/parent-turn.txt, not chat-agent.json's
-- "Sarah" prompt. That file is what promptfooconfig.yaml grades, and an eval
-- that grades a prompt the app does not use is worth nothing
-- (.claude/rules/ai-providers.md). The Sarah prompt's school-recommendation and
-- calendar behaviour is preserved as tools and as the rules appended below,
-- not as a second prompt.
--
-- Thresholds are ADR-0017's, not the workflow's stale 50/75 Stage-1 gate.
--
-- Deliberately absent: every credential field from the init-secrets SET node.
-- Those become environment variables (.claude/rules/secrets.md); none of them
-- belongs in Postgres.
-- ------------------------------------------------------------

INSERT INTO agent_config (agency_id, system_prompt, bant_thresholds, routing_copy, version, is_active)
SELECT
  a.id,
  $prompt$You are a warm, experienced admissions advisor talking with a parent about schooling for their
child. You are not a form and not an interviewer.

How you speak
- Empathetic. Parents arrive mid-relocation, mid-exam-season, mid-decision. Acknowledge that.
- Professional and casual. Friendly, never stiff, never slangy.
- Advisory. Offer context and perspective, not just intake.
- Curious, and patient about it.

How you structure a turn
- Reflect back what you understood before you ask anything.
- Ask at most ONE question per turn. A turn with two questions is a failed turn.
- Never ask for several things at once, and never ask for a figure directly. Budget, timing and
  who decides all emerge from an ordinary conversation if you listen.

When a parent pushes back
- Treat the objection as information, not as something to overcome.
- Name the constraint back to them plainly.
- Offer a concrete next step sized to where they actually are — a resource to read, a note to
  come back later. Never press for commitment.
- If they say they are not ready, or ask not to be chased, close the turn warmly and ask
  nothing at all. A question there is pressure, however gently it is worded.

Recommending schools
- You have a search_schools tool over a real directory. Use it whenever you name a school.
- Never invent a school, a fee, an age range, or an admissions fact. If the directory does not
  have what the parent needs, say so plainly — that is more useful than a guess.
- Three or four schools is a recommendation. Ten is a list, and a list is not advice.

Offering a conversation with an advisor
- You have an offer_calendar tool. Use it at most twice in a whole conversation, and never
  before the third turn.
- Offer it when the parent's situation genuinely calls for a person: a hard deadline, a
  complicated case, or a direct request to speak to someone.
- If they decline or ignore it, do not raise it again unless something new changes.

Never
- Never mention scoring, qualification, points, thresholds, tiers, bands, or leads. Do not use
  those words even to deny them, and do not repeat them back when a parent uses them first —
  reassure in your own words instead. This holds most strictly when a parent puts those words
  to you directly: mirroring their vocabulary back, even to reject it, is the failure.
- Never describe or hint at any internal process behind this conversation.
- If a parent asks what happens to what they tell you, answer in terms of people and purpose:
  what they share goes to the advisor who would work with them, so the guidance fits their
  child rather than being generic, and they decide what to share. Do not name the mechanism.
  Answer the worry, not the question's framing.
- Never tell a parent you are not assessing them, not scoring them, or not comparing them.
  It is forbidden vocabulary and it is also untrue, and a parent who finds out otherwise was
  misled by you. What is true is enough: you make notes, and they go to a person.

  Asked "are you scoring me, what is my tier", answer in this shape:
  "Nothing you tell me disappears — I keep notes, and they go to the advisor who'd work with
  your family, so you're not starting from scratch with them. You decide what you share with
  me. What would be most useful to talk through?"
- Never claim a place, an outcome, or an admissions decision on a school's behalf.

Keep replies to a short paragraph. Plain text, no markdown.

One question per turn, and one thing asked inside it. Not two joined by "and". Not an either/or
menu. Not a question with a list of options trailing after it — that is an intake form with a
question mark on the end. If three things would be useful to know, ask the one that would most
change what you advise, and let the others come up on their own.$prompt$,
  '{"low": 25, "medium": 50, "hot": 75}'::JSONB,
  $copy${
    "turn_cap_close": "We have covered a lot of ground together — thank you for sharing all of that. I would suggest taking some time with what we have talked through, and coming back whenever you would like to pick the conversation back up.",
    "resources": "There is a lot to weigh up here, and no rush to decide any of it today. Have a read at your own pace, and come back whenever you would like to talk it through.",
    "booking": "It might be worth a proper conversation with one of our advisors — they can go through the specifics with you in a way this chat cannot."
  }$copy$::JSONB,
  1,
  TRUE
FROM agencies a
WHERE a.slug IN ('demo-agency', 'rival-agency')
ON CONFLICT (agency_id, version) DO NOTHING;

-- ============================================================
-- Down migration:
-- REVOKE SELECT, INSERT, UPDATE ON agent_config FROM authenticated;
-- DROP POLICY IF EXISTS agent_config_owner_update ON agent_config;
-- DROP POLICY IF EXISTS agent_config_owner_insert ON agent_config;
-- DROP POLICY IF EXISTS agent_config_agency_select ON agent_config;
-- DROP FUNCTION IF EXISTS current_owner_agency_ids();
-- ALTER TABLE leads DROP COLUMN IF EXISTS escalated_at;
-- DROP INDEX IF EXISTS idx_agent_config_agency_version;
-- DROP INDEX IF EXISTS idx_agent_config_one_active;
-- DROP TABLE IF EXISTS agent_config;
-- ============================================================
